version: "3.8"

services:
  jose:
    build: ./apps/jrm0042
    container_name: app_jose
    ports:
      - "5000:5000"
    restart: unless-stopped

  javier:
    build: ./apps/jcs0032
    container_name: app_javier
    ports:
      - "5001:5001"
    restart: unless-stopped

  jesus:
    build: ./apps/JesusJhoan17
    container_name: app_jesus
    ports:
      - "5002:5002"
    restart: unless-stopped

  nginx_reverse:
    image: nginx:stable
    container_name: nginx_reverse
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/htpasswd/htpasswd_jose:/etc/nginx/htpasswd/htpasswd_jose:ro
      - ../nginx/htpasswd/htpasswd_javier:/etc/nginx/htpasswd/htpasswd_javier:ro
      - ../nginx/htpasswd/htpasswd_jesus:/etc/nginx/htpasswd/htpasswd_jesus:ro
    depends_on:
      - jose
      - javier
      - jesus
    restart: unless-stopped





